# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a6d04581ccc6aa44c921bd3f78c6edcd19dcc9223c190a3b96364e23edb3d0ded46a5eebd583200fc4955145bf5a6f458065a375a00039bea41cc70198b8785

test:
  secret_key_base: 4a059bde1089f58889357c2a25e2ecc490917d245fcc34b7d39a02cc3fd0537170e633621c112a696681c55b560f8eb88ac8a25952cbd697378894200b986946

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
